mysql:
  image: mysql:5.7
  container_name: mysql
  environment:
    MYSQL_DATABASE: 'mysql'
    MYSQL_USER: 'root'
    MYSQL_PASSWORD: '12345678'
    MYSQL_ROOT_PASSWORD: '12345678'
  ports:
    - "3306:3306"
  volumes:
    - ${MYSQL_DATA_DIRECTORY}/conf.d:/etc/mysql/conf.d
    - ${MYSQL_DATA_DIRECTORY}/logs:/logs
    - ${MYSQL_DATA_DIRECTORY}/data:/var/lib/mysql