version: '3.5'
services:
  postgresql:
    image: postgres:14.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRESQL_DATA_DIRECTORY}/data:/var/lib/postgresql/data
