version: '3'
services:
  postgresql:
    image: postgres:14.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8432:5432" # using 8432 to avoid the default psql port
    volumes:
      - ${POSTGRESQL_DATA_DIRECTORY}/data:/var/lib/postgresql/data